FROM python:3.11-slim-bullseye

WORKDIR /GradProject

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential cmake libatlas-base-dev libopenblas-dev \
    liblapack-dev libjpeg-dev libpng-dev libfreetype6-dev pkg-config \
 && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Default command
CMD ["python", "main.py"]
